version: "3.9"
services:
  bdd: 
    container_name: freeflow-bdd
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - db:/data/postgres
    environment: 
      POSTGRES_USER: freeflow
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: freeflow
 api:
    image: ghcr.io/eikjos/freeflow-api:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      DB_HOST: bdd
      DB_PORT: 5432
      DB_USER: freeflow
      DB_NAME: freeflow
      SMTP_URL: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: thomashamelin3@gmail.com
      CLIENT_URL: ${CLIENT_URL}
    secrets:
      - source: db_password
        target: DB_PASSWORD
      - source: jwt_secret
        target: SECRET_JWT
      - source: jwt_refresh_secret
        target: JWT_REFRESH_SECRET
      - source: insee_api_key
        target: INSEE_API_KEY
      - source: smtp_password
        target: SMTP_PASSWORD
    ports:
      - "8080:8080"
    depends_on: 
      - bdd

  web:
    container_name: freeflow-web
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      target: web
      args:
        API_URL: ${API_URL}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      API_URL: ${API_URL}
      NEXT_PUBLIC_API_URL: /api

volumes:
  db:
